// Generated by gencpp from file arm_controller/ArmResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_ARMRESPONSE_H
#define ARM_CONTROLLER_MESSAGE_ARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct ArmResponse_
{
  typedef ArmResponse_<ContainerAllocator> Type;

  ArmResponse_()
    : resultArm(false)
    , status(0)  {
    }
  ArmResponse_(const ContainerAllocator& _alloc)
    : resultArm(false)
    , status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _resultArm_type;
  _resultArm_type resultArm;

   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::arm_controller::ArmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::ArmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmResponse_

typedef ::arm_controller::ArmResponse_<std::allocator<void> > ArmResponse;

typedef boost::shared_ptr< ::arm_controller::ArmResponse > ArmResponsePtr;
typedef boost::shared_ptr< ::arm_controller::ArmResponse const> ArmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::ArmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::ArmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::ArmResponse_<ContainerAllocator1> & lhs, const ::arm_controller::ArmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resultArm == rhs.resultArm &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::ArmResponse_<ContainerAllocator1> & lhs, const ::arm_controller::ArmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::ArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::ArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::ArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::ArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::ArmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::ArmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::ArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7573387fab88d9bcb19d95022c6b9cce";
  }

  static const char* value(const ::arm_controller::ArmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7573387fab88d9bcULL;
  static const uint64_t static_value2 = 0xb19d95022c6b9cceULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::ArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/ArmResponse";
  }

  static const char* value(const ::arm_controller::ArmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::ArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool resultArm\n"
"int8 status\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::arm_controller::ArmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::ArmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultArm);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::ArmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::ArmResponse_<ContainerAllocator>& v)
  {
    s << indent << "resultArm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resultArm);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_ARMRESPONSE_H
