// Generated by gencpp from file arm_controller/buttonStatusResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_BUTTONSTATUSRESPONSE_H
#define ARM_CONTROLLER_MESSAGE_BUTTONSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct buttonStatusResponse_
{
  typedef buttonStatusResponse_<ContainerAllocator> Type;

  buttonStatusResponse_()
    : isActive(false)  {
    }
  buttonStatusResponse_(const ContainerAllocator& _alloc)
    : isActive(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isActive_type;
  _isActive_type isActive;





  typedef boost::shared_ptr< ::arm_controller::buttonStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::buttonStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct buttonStatusResponse_

typedef ::arm_controller::buttonStatusResponse_<std::allocator<void> > buttonStatusResponse;

typedef boost::shared_ptr< ::arm_controller::buttonStatusResponse > buttonStatusResponsePtr;
typedef boost::shared_ptr< ::arm_controller::buttonStatusResponse const> buttonStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::buttonStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::buttonStatusResponse_<ContainerAllocator1> & lhs, const ::arm_controller::buttonStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isActive == rhs.isActive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::buttonStatusResponse_<ContainerAllocator1> & lhs, const ::arm_controller::buttonStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::buttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::buttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::buttonStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74c71bbe95320ceee0e02ceb6900a4a1";
  }

  static const char* value(const ::arm_controller::buttonStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74c71bbe95320ceeULL;
  static const uint64_t static_value2 = 0xe0e02ceb6900a4a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/buttonStatusResponse";
  }

  static const char* value(const ::arm_controller::buttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isActive\n"
"\n"
;
  }

  static const char* value(const ::arm_controller::buttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isActive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buttonStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::buttonStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::buttonStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "isActive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isActive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_BUTTONSTATUSRESPONSE_H
