// Generated by gencpp from file arm_controller/buttonStatusRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_BUTTONSTATUSREQUEST_H
#define ARM_CONTROLLER_MESSAGE_BUTTONSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct buttonStatusRequest_
{
  typedef buttonStatusRequest_<ContainerAllocator> Type;

  buttonStatusRequest_()
    : resultButton(false)  {
    }
  buttonStatusRequest_(const ContainerAllocator& _alloc)
    : resultButton(false)  {
  (void)_alloc;
    }



   typedef uint8_t _resultButton_type;
  _resultButton_type resultButton;





  typedef boost::shared_ptr< ::arm_controller::buttonStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::buttonStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct buttonStatusRequest_

typedef ::arm_controller::buttonStatusRequest_<std::allocator<void> > buttonStatusRequest;

typedef boost::shared_ptr< ::arm_controller::buttonStatusRequest > buttonStatusRequestPtr;
typedef boost::shared_ptr< ::arm_controller::buttonStatusRequest const> buttonStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::buttonStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::buttonStatusRequest_<ContainerAllocator1> & lhs, const ::arm_controller::buttonStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.resultButton == rhs.resultButton;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::buttonStatusRequest_<ContainerAllocator1> & lhs, const ::arm_controller::buttonStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::buttonStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::buttonStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::buttonStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a085941e12cf0ecf068cec1e4ba06f9";
  }

  static const char* value(const ::arm_controller::buttonStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a085941e12cf0ecULL;
  static const uint64_t static_value2 = 0xf068cec1e4ba06f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/buttonStatusRequest";
  }

  static const char* value(const ::arm_controller::buttonStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool resultButton\n"
;
  }

  static const char* value(const ::arm_controller::buttonStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultButton);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buttonStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::buttonStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::buttonStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "resultButton: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resultButton);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_BUTTONSTATUSREQUEST_H
