// Generated by gencpp from file arm_controller/buttonStatus.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_BUTTONSTATUS_H
#define ARM_CONTROLLER_MESSAGE_BUTTONSTATUS_H

#include <ros/service_traits.h>


#include <arm_controller/buttonStatusRequest.h>
#include <arm_controller/buttonStatusResponse.h>


namespace arm_controller
{

struct buttonStatus
{

typedef buttonStatusRequest Request;
typedef buttonStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct buttonStatus
} // namespace arm_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_controller::buttonStatus > {
  static const char* value()
  {
    return "96a1c76b0629b71c9a214609600d9e41";
  }

  static const char* value(const ::arm_controller::buttonStatus&) { return value(); }
};

template<>
struct DataType< ::arm_controller::buttonStatus > {
  static const char* value()
  {
    return "arm_controller/buttonStatus";
  }

  static const char* value(const ::arm_controller::buttonStatus&) { return value(); }
};


// service_traits::MD5Sum< ::arm_controller::buttonStatusRequest> should match
// service_traits::MD5Sum< ::arm_controller::buttonStatus >
template<>
struct MD5Sum< ::arm_controller::buttonStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_controller::buttonStatus >::value();
  }
  static const char* value(const ::arm_controller::buttonStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_controller::buttonStatusRequest> should match
// service_traits::DataType< ::arm_controller::buttonStatus >
template<>
struct DataType< ::arm_controller::buttonStatusRequest>
{
  static const char* value()
  {
    return DataType< ::arm_controller::buttonStatus >::value();
  }
  static const char* value(const ::arm_controller::buttonStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_controller::buttonStatusResponse> should match
// service_traits::MD5Sum< ::arm_controller::buttonStatus >
template<>
struct MD5Sum< ::arm_controller::buttonStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_controller::buttonStatus >::value();
  }
  static const char* value(const ::arm_controller::buttonStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_controller::buttonStatusResponse> should match
// service_traits::DataType< ::arm_controller::buttonStatus >
template<>
struct DataType< ::arm_controller::buttonStatusResponse>
{
  static const char* value()
  {
    return DataType< ::arm_controller::buttonStatus >::value();
  }
  static const char* value(const ::arm_controller::buttonStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_BUTTONSTATUS_H
