// Generated by gencpp from file arm_controller/HMIResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_HMIRESPONSE_H
#define ARM_CONTROLLER_MESSAGE_HMIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct HMIResponse_
{
  typedef HMIResponse_<ContainerAllocator> Type;

  HMIResponse_()
    : codeHMI(0)  {
    }
  HMIResponse_(const ContainerAllocator& _alloc)
    : codeHMI(0)  {
  (void)_alloc;
    }



   typedef int64_t _codeHMI_type;
  _codeHMI_type codeHMI;





  typedef boost::shared_ptr< ::arm_controller::HMIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::HMIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HMIResponse_

typedef ::arm_controller::HMIResponse_<std::allocator<void> > HMIResponse;

typedef boost::shared_ptr< ::arm_controller::HMIResponse > HMIResponsePtr;
typedef boost::shared_ptr< ::arm_controller::HMIResponse const> HMIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::HMIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::HMIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::HMIResponse_<ContainerAllocator1> & lhs, const ::arm_controller::HMIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.codeHMI == rhs.codeHMI;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::HMIResponse_<ContainerAllocator1> & lhs, const ::arm_controller::HMIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::HMIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::HMIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::HMIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::HMIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::HMIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::HMIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::HMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae9d7740bfbe2ee6afffd09422607821";
  }

  static const char* value(const ::arm_controller::HMIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae9d7740bfbe2ee6ULL;
  static const uint64_t static_value2 = 0xafffd09422607821ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::HMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/HMIResponse";
  }

  static const char* value(const ::arm_controller::HMIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::HMIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 codeHMI\n"
"\n"
"\n"
;
  }

  static const char* value(const ::arm_controller::HMIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::HMIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.codeHMI);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HMIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::HMIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::HMIResponse_<ContainerAllocator>& v)
  {
    s << indent << "codeHMI: ";
    Printer<int64_t>::stream(s, indent + "  ", v.codeHMI);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_HMIRESPONSE_H
