// Generated by gencpp from file arm_controller/VisionRequest.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_VISIONREQUEST_H
#define ARM_CONTROLLER_MESSAGE_VISIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct VisionRequest_
{
  typedef VisionRequest_<ContainerAllocator> Type;

  VisionRequest_()
    : resultVision(false)  {
    }
  VisionRequest_(const ContainerAllocator& _alloc)
    : resultVision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _resultVision_type;
  _resultVision_type resultVision;





  typedef boost::shared_ptr< ::arm_controller::VisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::VisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VisionRequest_

typedef ::arm_controller::VisionRequest_<std::allocator<void> > VisionRequest;

typedef boost::shared_ptr< ::arm_controller::VisionRequest > VisionRequestPtr;
typedef boost::shared_ptr< ::arm_controller::VisionRequest const> VisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::VisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::VisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::VisionRequest_<ContainerAllocator1> & lhs, const ::arm_controller::VisionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.resultVision == rhs.resultVision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::VisionRequest_<ContainerAllocator1> & lhs, const ::arm_controller::VisionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::VisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::VisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::VisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::VisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::VisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::VisionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::VisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cae9d96f75a4015a06a54ce67a731295";
  }

  static const char* value(const ::arm_controller::VisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcae9d96f75a4015aULL;
  static const uint64_t static_value2 = 0x06a54ce67a731295ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::VisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/VisionRequest";
  }

  static const char* value(const ::arm_controller::VisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::VisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool resultVision\n"
;
  }

  static const char* value(const ::arm_controller::VisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::VisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultVision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::VisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::VisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "resultVision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resultVision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_VISIONREQUEST_H
