// Generated by gencpp from file arm_controller/VisionResponse.msg
// DO NOT EDIT!


#ifndef ARM_CONTROLLER_MESSAGE_VISIONRESPONSE_H
#define ARM_CONTROLLER_MESSAGE_VISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_controller
{
template <class ContainerAllocator>
struct VisionResponse_
{
  typedef VisionResponse_<ContainerAllocator> Type;

  VisionResponse_()
    : x(0.0)
    , y(0.0)
    , z(false)
    , isActive(false)  {
    }
  VisionResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(false)
    , isActive(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _z_type;
  _z_type z;

   typedef uint8_t _isActive_type;
  _isActive_type isActive;





  typedef boost::shared_ptr< ::arm_controller::VisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller::VisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisionResponse_

typedef ::arm_controller::VisionResponse_<std::allocator<void> > VisionResponse;

typedef boost::shared_ptr< ::arm_controller::VisionResponse > VisionResponsePtr;
typedef boost::shared_ptr< ::arm_controller::VisionResponse const> VisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_controller::VisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_controller::VisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_controller::VisionResponse_<ContainerAllocator1> & lhs, const ::arm_controller::VisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.isActive == rhs.isActive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_controller::VisionResponse_<ContainerAllocator1> & lhs, const ::arm_controller::VisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_controller::VisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_controller::VisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::VisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_controller::VisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::VisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_controller::VisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_controller::VisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8b756d1256b16c19068251ed7cca845";
  }

  static const char* value(const ::arm_controller::VisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8b756d1256b16c1ULL;
  static const uint64_t static_value2 = 0x9068251ed7cca845ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller::VisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_controller/VisionResponse";
  }

  static const char* value(const ::arm_controller::VisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_controller::VisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"bool z\n"
"bool isActive\n"
;
  }

  static const char* value(const ::arm_controller::VisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_controller::VisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.isActive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller::VisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_controller::VisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.z);
    s << indent << "isActive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isActive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MESSAGE_VISIONRESPONSE_H
